name: salawati
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.7
  dio: ^5.7.0
  intl: ^0.19.0
  connectivity_plus: ^6.1.0
  flutter_offline: ^4.0.0
  device_preview: ^1.2.0
  flutter_screenutil: ^5.9.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.5
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: 'assets/icon/icon.png'
  adaptive_icon_background: 'assets/icon/icon.png'
flutter_native_splash:
  color: "#CCCECB"  # اللون الأبيض
  image: "assets/intro/intro_image.png"  # المسار الصحيح لصورة شاشة البداية
  android: true
  ios: true
  analyzer: ^6.11.0
flutter:
  uses-material-design: true
  assets:
    - assets/intro/intro_image.png  # تأكد من إضافة الصورة للمسار الصحيح
    - assets/icon/icon.png
  fonts:
    - family: Amiri-Regular
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
